name: Plugin check
on:
  push:
    branches: [ 'master', 'release/*' ]
  pull_request:
    branches: [ 'master' ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Package plugin
        run: |
          mkdir -p dist/blacklist-updater
          git archive HEAD | tar x --directory=dist/blacklist-updater

      - name: Check WP plugin
        uses: wordpress/plugin-check-action@v1
        with:
          build-dir: dist/blacklist-updater
